apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wingert.fullname" . }}-backend
  labels:
    {{- include "wingert.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "wingert.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "wingert.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            {{- range $k, $v := .Values.backend.env }}
            {{- if and (ne $k "DB_PASSWORD") (ne $k "JWT_SECRET") (ne $k "DB_HOST") }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            {{- end }}
            - name: DB_HOST
              value: {{ include "wingert.fullname" . }}-postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wingert.fullname" . }}-secrets
                  key: db-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "wingert.fullname" . }}-secrets
                  key: jwt-secret
            - name: S3_ENDPOINT
              value: {{ printf "http://%s-minio:9000" (include "wingert.fullname" .) | quote }}
            - name: S3_BUCKET
              value: {{ .Values.minio.bucket | quote }}
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "wingert.fullname" . }}-secrets
                  key: minio-root-user
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "wingert.fullname" . }}-secrets
                  key: minio-root-password
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
