apiVersion: v1
kind: Service
metadata:
  name: {{ include "wingert.fullname" . }}-backend
  labels:
    {{- include "wingert.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    {{- include "wingert.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - port: 8080
      targetPort: 8080
