apiVersion: v1
kind: Service
metadata:
  name: {{ include "wingert.fullname" . }}-frontend
  labels:
    {{- include "wingert.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    {{- include "wingert.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - port: 80
      targetPort: 80
