apiVersion: v1
kind: Service
metadata:
  name: {{ include "wingert.fullname" . }}-postgres
  labels:
    {{- include "wingert.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  selector:
    {{- include "wingert.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
