apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wingert.fullname" . }}-backups
  labels:
    {{- include "wingert.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backup.storage }}
