apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wingert.fullname" . }}-secrets
  labels:
    {{- include "wingert.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.postgres.env.POSTGRES_PASSWORD | quote }}
  jwt-secret: {{ .Values.backend.env.JWT_SECRET | quote }}
  minio-root-user: {{ .Values.minio.rootUser | quote }}
  minio-root-password: {{ .Values.minio.rootPassword | quote }}
