ALTER TABLE tasks DROP COLUMN IF EXISTS type;
ALTER TABLE tasks
  ADD COLUMN IF NOT EXISTS record_type TEXT NOT NULL DEFAULT 'aufgabe',
  ADD COLUMN IF NOT EXISTS category    TEXT NOT NULL DEFAULT 'sonstiges',
  ADD COLUMN IF NOT EXISTS severity    TEXT,
  ADD COLUMN IF NOT EXISTS phase       TEXT;
